#!/bin/bash
setxkbmap dvorak -option ctrl:nocaps
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

# xcape allows you to make mod keys do things when pressed on their own
# https://github.com/alols/xcape.git
if type xcape >/dev/null 2>&1;then
    xcape -e 'Control_L=Escape'
fi
# Set any custom keybindings
if type xbindkeys >/dev/null 2>&1;then
    xbindkeys
fi

# Start xscreensaver server
if type xscreensaver >/dev/null 2>&1;then
    xscreensaver -nosplash &
fi

# prevents use of the trackpad for a quarter of a second after you stop typing
if type syndaemon >/dev/null 2>&1;then
    syndaemon -i 0.25 -K -d
fi

# flux -- automatically adjust brightness based on time of day (easy on the eyes)
if type xflux >/dev/null 2>&1;then
    xflux -z 98312
fi
exec awesome -c /home/miles/.config/awesome/rc.lua
